In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


# Numpy


In [3]:
import numpy as np

In [4]:
# The basic np array

a = np.arange(6)
print(f"{a} is {type(a)}")
alist = a.tolist()
print(f"{alist} is {type(alist)}")

[0 1 2 3 4 5] is <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5] is <class 'list'>


In [5]:
print(["hi", 1, 2])
print(np.array(["hi", 1, 2]))  # this works but makes things inefficient

['hi', 1, 2]
['hi' '1' '2']


In [6]:
ndarr = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]])
print(ndarr)
print(ndarr.dtype)
print(ndarr.size)
print(ndarr.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
int64
12
(3, 4)


In [7]:
print(np.empty((3, 3)))
print(np.arange(-10, 10, 2))
print(np.linspace(-10, 10, 13))

[[ 6.17779239e-31 -1.23555848e-30  3.08889620e-31]
 [-1.23555848e-30  2.68733969e-30 -8.34001973e-31]
 [ 3.08889620e-31 -8.34001973e-31  4.78778910e-31]]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[-10.          -8.33333333  -6.66666667  -5.          -3.33333333
  -1.66666667   0.           1.66666667   3.33333333   5.
   6.66666667   8.33333333  10.        ]


In [8]:
print(np.array([1.1, 2], dtype=np.int8))

[1 2]


In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b.T), axis=1)
print(c)
print(c[0][1])
print(c.shape)
print(d)
print(d.shape)
e = c.reshape(d.shape)
print(e)
f = np.reshape(c, newshape=d.shape, order="F")
print(f)
g = np.reshape(c, newshape=d.shape, order="A")
print(g)
h = c.T
print(h)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
[[1 2 5]
 [3 4 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 5 4]
 [3 2 6]]
[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [39]:
i = np.concatenate((c, b))
print(i)
print(i.shape)
j = i.reshape((2, 2, 2))
print(j)
print(j.shape)
k = i[
    :,
    np.newaxis,
]  # Looks like this can't reshape but just add an extra single element dimension
print(k)
print(k.shape)
print(k.size)

[[1 2]
 [3 4]
 [5 6]
 [5 6]]
(4, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [5 6]]]
(2, 2, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[5 6]]]
(4, 1, 2)
8


In [50]:
a = np.array([[4, 3], [1, 2]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b.T), axis=1)
print(c)
print(c.shape)
print(d)
print(d.shape)
print(np.sort(c))
print(np.sort(c, axis=0))
print(np.sort(c, axis=1))

[[4 3]
 [1 2]
 [5 6]]
(3, 2)
[[4 3 5]
 [1 2 6]]
(2, 3)
[[3 4]
 [1 2]
 [5 6]]
[[1 2]
 [4 3]
 [5 6]]
[[3 4]
 [1 2]
 [5 6]]


In [67]:
a = np.array([[4, 3], [1, 2]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print(c)
print(c[:, 1:2])
print(c[:, 2:1]) # no error
print(c[:, 1])
print(c[:, 1])
print(c[c >= 4])

[[4 3]
 [1 2]
 [5 6]]
[[3]
 [2]
 [6]]
[]
[3 2 6]
[3 2 6]
[4 5 6]


In [86]:
print(c)
d = np.hstack((c, c))
print(d)
e = np.vsplit(d, (2,)) # <-- returns a view so the same backing data
print(e)
e[0][0,0] = 10
print(d)

[[4 3]
 [1 2]
 [5 6]]
[[4 3 4 3]
 [1 2 1 2]
 [5 6 5 6]]
[array([[4, 3, 4, 3],
       [1, 2, 1, 2]]), array([[5, 6, 5, 6]])]
[[10  3  4  3]
 [ 1  2  1  2]
 [ 5  6  5  6]]


In [92]:
print(d.sum())
print(d.sum(axis=1))
print(d.sum(axis=0))
print(d.std(axis=1))
print(d.mean(axis=1))
print(d.prod(axis=1))
print(d.min(axis=1))

48
[20  6 22]
[16 11 10 11]
[2.91547595 0.5        0.5       ]
[5.  1.5 5.5]
[360   4 900]
[3 1 5]


In [90]:
print(d + 1)

[[11  4  5  4]
 [ 2  3  2  3]
 [ 6  7  6  7]]


In [109]:
rot90 = np.array([[0, 1], [-1, 0]])
print(rot90)
pt = np.array([0.5, 0.5]).reshape((2, 1));
print(pt)
print(rot90 * pt)
print(np.matmul(rot90, pt))
print(rot90 + pt)

[[ 0  1]
 [-1  0]]
[[0.5]
 [0.5]]
[[ 0.   0.5]
 [-0.5  0. ]]
[[ 0.5]
 [-0.5]]
[[ 0.5  1.5]
 [-0.5  0.5]]


In [115]:
print(np.expand_dims(np.array([1, 2]), axis=0).T)
print(np.array([[1, 2]]).T)

[[1]
 [2]]
[[1]
 [2]]


In [121]:
print(d)
print(np.flip(d))
print(np.flip(d, axis=0))
print(np.flip(d, axis=1))

[[10  3  4  3]
 [ 1  2  1  2]
 [ 5  6  5  6]]
[[ 6  5  6  5]
 [ 2  1  2  1]
 [ 3  4  3 10]]
[[ 5  6  5  6]
 [ 1  2  1  2]
 [10  3  4  3]]
[[ 3  4  3 10]
 [ 2  1  2  1]
 [ 6  5  6  5]]


In [123]:
print(d.flatten()) # new nparr
print(d.ravel()) # view

[10  3  4  3  1  2  1  2  5  6  5  6]
[10  3  4  3  1  2  1  2  5  6  5  6]


In [124]:
d

Type:        ndarray
String form:
[[10  3  4  3]
 [ 1  2  1  2]
 [ 5  6  5  6]]
Length:      3
File:        ~/fiddles/pytorch_explore/.conda/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created

In [125]:
d

Type:        ndarray
String form:
[[10  3  4  3]
 [ 1  2  1  2]
 [ 5  6  5  6]]
Length:      3
File:        ~/fiddles/pytorch_explore/.conda/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created