In [1]:
import numpy as np

In [10]:
class Layer:
    def __init__(self, input_size, num_nodes) -> None:
        self.w = np.random.rand(num_nodes, input_size)
        self.b = np.random.rand(num_nodes, 1)

    def forward(self, batch):
        return np.matmul(self.w, batch) + self.b

In [20]:
input_size = 3
output_size = 4
batch_size = 10

l = Layer(input_size, output_size)
print(l.w)
print(l.b)
input1 = np.ones((input_size, batch_size))
print(input1)
print(l.forward(input1))
print(np.mean(l.forward(input1), axis=1))

[[0.65037432 0.92510431 0.41783981]
 [0.62640228 0.68410345 0.85295562]
 [0.70074065 0.93311316 0.20845583]
 [0.32386497 0.6581439  0.30184392]]
[[0.57531002]
 [0.86978512]
 [0.62842034]
 [0.93010683]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[2.56862846 2.56862846 2.56862846 2.56862846 2.56862846 2.56862846
  2.56862846 2.56862846 2.56862846 2.56862846]
 [3.03324648 3.03324648 3.03324648 3.03324648 3.03324648 3.03324648
  3.03324648 3.03324648 3.03324648 3.03324648]
 [2.47072999 2.47072999 2.47072999 2.47072999 2.47072999 2.47072999
  2.47072999 2.47072999 2.47072999 2.47072999]
 [2.21395962 2.21395962 2.21395962 2.21395962 2.21395962 2.21395962
  2.21395962 2.21395962 2.21395962 2.21395962]]
[2.56862846 3.03324648 2.47072999 2.21395962]
